### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by kucherenkovova** [mixomat/ng2-resizable#1]
I cloned the project. Then `npm i` in `examples\webpack`, then `npm start` and here's what I get

```
(1,10): error TS2661: Cannot re-export name that is not defined in the module.

ERROR in ./src/app.ts
(4,25): error TS2307: Cannot find module 'ng2-resizable/ng2-resizable'.

ERROR in ./src/app.ts
Module not found: Error: Cannot resolve module 'ng2-resizable/ng2-resizable' in D:\projects\ng2-resizable\ng2-resizable\examples\webpack\src
 @ ./src/app.ts 14:22-60
```

I'm using Windows 10

**Comment by mixomat** [comment]
@kucherenkovova this repo hasn't been updated since the angular beta phase. Will update it to the latest module syntax.

**Comment by rkgomekar** [comment]
Doesn't work with Angular 2.0 final release....
